parameters:
- name: docker_registry_address
  displayName: docker_registry_address
  type: string
  default: intelligentvoice.azurecr.io
steps:
- task: AzureCLI@2
  name: registrycredentials
  displayName: Generate registry credentials
  inputs:
    azureSubscription: Azure-nightly-tests
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      acrpassword=$(az acr login --name ${DOCKER_REGISTRY_ADDRESS} --expose-token --output tsv --query accessToken)
      if [[ "$acrpassword" == *ERROR:* ]] || [[ "$acrpassword" == *Error:* ]]; then
        echo "Error occurred while requesting credentials:"
        echo "$acrpassword"
        exit 1
      fi
      echo "##vso[task.setvariable variable=temporaryregistrypassword;isoutput=true]$acrpassword"