- name: Capture VM Images
  hosts: localhost
  connection: local
  vars:
    shared_gallery_name: "iv_shared_gallery{{ vm_suffix | replace('-', '_') }}"
    gallery_image_version: "{{image_version | default('1.0.0') }}"
    vm_list:
      - vm_name: ASR{{ vm_suffix }}
        vm_size: Standard_NC4as_T4_v3
      - vm_name: Diarization{{ vm_suffix }}
        vm_size: Standard_NC4as_T4_v3
      - vm_name: LexiQal{{ vm_suffix }}
        vm_size: Standard_F2s_v2
      - vm_name: LMBuilder{{ vm_suffix }}
        vm_size: Standard_F2s_v2
      - vm_name: Sentiment{{ vm_suffix }}
        vm_size: Standard_NC4as_T4_v3
      - vm_name: Tagger{{ vm_suffix }}
        vm_size: Standard_E2as_v5
      - vm_name: VAD{{ vm_suffix }}
        vm_size: Standard_F2s_v2
      - vm_name: VoiceBiometric{{ vm_suffix }}
        vm_size: Standard_F2s_v2
  tasks:
    - name: Create shared image gallery
      azure.azcollection.azure_rm_gallery:
        resource_group: "{{ resource_group }}"
        name: "{{ shared_gallery_name }}"
        location: "{{ azure_region | default('uksouth') }}"
        description: Shared Image Gallery for IV images
    - name: Stop and generalize VMs
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: '{{ resource_group }}'
        name: '{{ item.vm_name }}'
        generalized: 'yes'
      loop: '{{ vm_list }}'
    - name: Create images from VMs
      azure.azcollection.azure_rm_image:
        resource_group: '{{ resource_group }}'
        name: 'image_{{ item.vm_name }}'
        source: '{{ item.vm_name }}'
      loop: '{{ vm_list }}'
      loop_control:
        label: 'image_{{ item.vm_name }}'
      register: image_results
    - name: Create shared images
      azure.azcollection.azure_rm_galleryimage:
        resource_group: "{{ resource_group }}"
        gallery_name: "{{ shared_gallery_name }}"
        name: 'image_{{ item.vm_name }}'
        location: "{{ azure_region | default('uksouth') }}"
        os_type: linux
        os_state: generalized
        identifier:
          publisher: IntelligentVoice
          offer: IntelligentVoice
          sku: '{{ item.vm_name }}'
        description: '{{ item.vm_name }}'
      loop: '{{ vm_list }}'
      loop_control:
        label: 'image_{{ item.vm_name }}'

    - name: Check if the gallery image version exists
      azure.azcollection.azure_rm_galleryimageversion_info:
        resource_group: "{{ resource_group }}"
        gallery_name: "{{ shared_gallery_name }}"
        gallery_image_name: 'image_{{ item.vm_name }}'
      register: existing_versions
      loop: '{{ vm_list }}'
      loop_control:
        label: 'image_{{ item.vm_name }}'
        index_var: loop_index

    - name: Create or update a gallery image version
      azure.azcollection.azure_rm_galleryimageversion:
        resource_group: "{{ resource_group }}"
        gallery_name: "{{ shared_gallery_name }}"
        gallery_image_name: 'image_{{ item.vm_name }}'
        name: "{{ gallery_image_version }}"
        location: "{{ azure_region | default('UK South') }}"
        publishing_profile:
          replica_count: 1
          target_regions:
            - name: "{{ azure_region | default('UK South') }}"
              regional_replica_count: 1
              storage_account_type: Standard_LRS
          storage_account_type: Standard_LRS
        storage_profile:
          source_image: "{{ image_results.results[loop_index].id }}"
      when: "gallery_image_version not in existing_versions.results | map(attribute='name')"
      loop: '{{ vm_list }}'
      loop_control:
        label: 'image_{{ item.vm_name }}'
        index_var: loop_index
      register: version_results

    - name: Create a scale set
      azure.azcollection.azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: 'vmss_{{ item.vm_name }}'
        vm_size: '{{ item.vm_size }}'
        capacity: 1
        priority: Spot
        eviction_policy: Deallocate
        upgrade_policy: Manual
        tier: Standard
        managed_disk_type: Standard_LRS
        virtual_network_name: "VNET{{ vm_suffix }}"
        subnet_name: default
        image:
          id: "{{ version_results.results[loop_index].id }}"
      loop: '{{ vm_list }}'
      loop_control:
        index_var: loop_index
