# code: language=ansible
---
- name: Playbook to update OS
  hosts: all
  become: true
  tasks:
    - name: Distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"

    - name: "Upgrade OS with dnf"
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_only: true
      register: upgrade_dnf
      retries: 6
      delay: 10
      until: upgrade_dnf is not failed
      when: ansible_os_family == 'RedHat'

    - name: "Upgrade OS with apt"
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      register: upgrade_apt
      retries: 6
      delay: 10
      until: upgrade_apt is not failed
      when: ansible_os_family == 'Debian'
