---
- name: Install Azure CLI
  hosts: localhost
  connection: local
  gather_facts: true
  gather_subset:
    - "distribution"
    - "architecture"
    - "!all"
    - "!min"
  tasks:
    - name: Check if 'az' command exists
      ansible.builtin.command: which az
      register: az_installed
      failed_when: false
      changed_when: false

    - name: Install python3-debian, required to use deb822_repository
      become: true
      ansible.builtin.apt:
        name: python3-debian
      when: az_installed.rc != 0

    - name: Install python-debian, because sometimes the previous task doesn't seem to work??
      ansible.builtin.pip:
        name: python-debian
      when: az_installed.rc != 0

    - name: Add Azure CLI repository
      become: true
      ansible.builtin.deb822_repository:
        name: azure-cli
        types: deb
        uris: https://packages.microsoft.com/repos/azure-cli/
        suites: "{{ ansible_distribution_release }}"
        components: main
        architectures: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
        signed_by: https://packages.microsoft.com/keys/microsoft.asc
      when: az_installed.rc != 0
      register: repo_result
      retries: 5
      delay: 10
      until: repo_result is not failed

    - name: Install Microsoft Azure CLI
      become: true
      ansible.builtin.apt:
        name: azure-cli=2.67.*
        update_cache: 'yes'
      when: az_installed.rc != 0
