[all-in-one]
AppServer instance_size=Standard_B8ms fail_worker_enabled=true

[core-servers] # According to the logic of the playbook should be empty, but present

[worker-servers]
ASR instance_size=Standard_NC4as_T4_v3 diarization_worker_enabled=true nvidia_runtime_enabled=true triton_server_enabled=true triton_server_docker_runtime=nvidia
Diarization instance_size=Standard_NC4as_T4_v3 diarization_worker_enabled=true nvidia_runtime_enabled=true triton_server_enabled=true triton_server_docker_runtime=nvidia
Credibility instance_size=Standard_F2s_v2 credibility_worker_enabled=true triton_server_enabled=true
LMBuilder instance_size=Standard_F2s_v2 lmbuilder_worker_enabled=true
Sentiment instance_size=Standard_NC4as_T4_v3 sentiment_worker_enabled=true nvidia_runtime_enabled=true triton_server_enabled=true triton_server_docker_runtime=nvidia
Summarisation instance_size=Standard_F2s_v2 transcript_summariser_worker_enabled=true
Tagger instance_size=Standard_E2as_v5 tagger_worker_enabled=true
VAD instance_size=Standard_F2s_v2 vad_worker_enabled=true

[all:vars]
docker_registry_login=00000000-0000-0000-0000-000000000000
docker_registry_password=#{dockerregistrypassword}#
basic_auth_username=models_user
basic_auth_password=#{basicauthpassword}#
application_domain=auto-scaling.example.com

gearman_server_address=10.0.0.5
iv_api_ip_address=10.0.0.5
sphinx_server_address=10.0.0.5
elasticsearch_server_address=10.0.0.5
opensearch_server_address=10.0.0.5

triton_server_enabled=false
asr_worker_enabled=false
diarization_worker_enabled=false
lmbuilder_worker_enabled=false
ocr_worker_enabled=false
tagger_worker_enabled=false
transcript_summariser_worker_enabled=false
vad_worker_enabled=false
sentiment_worker_enabled=false
credibility_worker_enabled=false
credibility_score_worker_enabled=false
fail_worker_enabled=false
voice_biometric_worker_enabled=false

vad_worker_count=2
diarization_worker_count=4
lmbuilder_worker_count=2
tagger_worker_count=2
transcript_summariser_worker_count=2
sentiment_worker_count=4
fail_worker_count=1